
name: Automatic publish to NPM
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'
      - name: Build (Pre-release check)
        run: |
         npm install
         npm run build
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release

      - name: Publish
        if: steps.release.outputs.released == 'true'
        run: |
         npm install
         npm run build
         npm publish dist/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
